name: Nightly build and test

on:
  schedule:
    - cron: '42 0 * * *'

jobs:
  build:

    runs-on: macos-14

    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
